FROM maven:3.8.4-openjdk-17-slim AS build

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline

COPY src ./src

COPY docker-dev-entry.sh ./

RUN chmod +x docker-dev-entry.sh

CMD ["./docker-dev-entry.sh"]